# $FreeBSD: projects/freebsd-update-server/src/Makefile,v 1.1 2006/08/31 07:48:41 cperciva Exp $

all:	findstamps unstamp

install:
	install findstamps ../bin
	install unstamp ../bin

clean:
	rm -f findstamps unstamp
